#+Title: General Style Guide
#+Author: Devin M. O'Brien
#+DATE: {INSERT DATE}

* What am I?
  This document is a general outline of the style of the directory
  structure as well as the coding style that is expected.

* Coding Style
** File Header 
   All source files require a file header.
** Magic Numbers
   Magic numbers will be defined as situations where the number used
   has a specific meaning. For example, if you have a loop that increases 
   a counter by 1, it will not be considered as a magic
   number. However, adding 97 to an integer to get an ascii character
   requires it to be a variable.

   Such variables should be defined at the beginning of the scope in
   which it is used. 
** Statements
** Methods
*** Method Descriptors
You may use a different style as long as the information is the same and it is used throughout the src file.
#+BEGIN_SRC js
/**
* SomeClass
*
* @desc An example for documentation.
* @method someMethod() 
**/
class SomeClass{
/* someMethod
* An example for a method
* @param[out] string Some string
*/
function someMethod(){
 return "Some String";
};

};
#+END_SRC
** Classes
** Documentation
* Documentation Directory
** Files
  - Project.tex: Project Documentation (.tex form)
  - Project.bib: Project Documentation Sources
  - Project.pdf: *Official* Project Documentation
  - Style.org:   (You Are Here!)
** Sub-Directories
*** data
    We don't have any data, but if we did, it would go here.
*** diagrams
    No one looks here, so don't worry.
**** Files
- Diagrams_Guide.org: Useless. Does it even exist?
**** Sub-Directories
***** src
      Arbitrary decision to place files that are used to make images, but not
      themselves images, go here.
***** out
      See above.
** File Types
| *Extension* | *Description*                                      |
|-------------+----------------------------------------------------|
| org         | Contains information to explain things informally? |
| pdf         | Formal Document.                                   |
| png         | Image                                              |
| bib         | Contains cites.                                    |
| tex         | Formal project documents.                          |
| plantuml    | Markup document, for diagrams.                     |
| md          | *How did this get in here?*                        |

Any violations will be listed here:
- dobrienUNCG: ~||||~ ~||||~ |
  1-7: Failure to update file extensions table after adding files
  8-11: Uploaded junk files


